// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSj-VgMO00ImwLFEFJ5JoVWpYzHUFKfm8',
    appId: '1:646841655886:web:98198b772ddcdd3902991f',
    messagingSenderId: '646841655886',
    projectId: 'sistemacompraschabely',
    authDomain: 'sistemacompraschabely.firebaseapp.com',
    databaseURL: 'https://sistemacompraschabely-default-rtdb.firebaseio.com',
    storageBucket: 'sistemacompraschabely.firebasestorage.app',
    measurementId: 'G-N8EJKZXG1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLBL4Y77HAJ4XHGsqn0bYwNUt2Zl6GlGI',
    appId: '1:646841655886:android:1db980686a21a5a002991f',
    messagingSenderId: '646841655886',
    projectId: 'sistemacompraschabely',
    databaseURL: 'https://sistemacompraschabely-default-rtdb.firebaseio.com',
    storageBucket: 'sistemacompraschabely.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8-mqDf9m4tjJlW3sQhI0Icy7beWhapa8',
    appId: '1:646841655886:ios:22c0e26b01518d7402991f',
    messagingSenderId: '646841655886',
    projectId: 'sistemacompraschabely',
    databaseURL: 'https://sistemacompraschabely-default-rtdb.firebaseio.com',
    storageBucket: 'sistemacompraschabely.firebasestorage.app',
    iosBundleId: 'com.example.sistemaCompras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8-mqDf9m4tjJlW3sQhI0Icy7beWhapa8',
    appId: '1:646841655886:ios:22c0e26b01518d7402991f',
    messagingSenderId: '646841655886',
    projectId: 'sistemacompraschabely',
    databaseURL: 'https://sistemacompraschabely-default-rtdb.firebaseio.com',
    storageBucket: 'sistemacompraschabely.firebasestorage.app',
    iosBundleId: 'com.example.sistemaCompras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSj-VgMO00ImwLFEFJ5JoVWpYzHUFKfm8',
    appId: '1:646841655886:web:d1156b9c00fb451002991f',
    messagingSenderId: '646841655886',
    projectId: 'sistemacompraschabely',
    authDomain: 'sistemacompraschabely.firebaseapp.com',
    databaseURL: 'https://sistemacompraschabely-default-rtdb.firebaseio.com',
    storageBucket: 'sistemacompraschabely.firebasestorage.app',
    measurementId: 'G-X83K59CHS7',
  );
}
