// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqGlqXBMHtpBBWX80MDNJXiFkU89spXpg',
    appId: '1:130125072749:web:e06da6a5477fc0698b7264',
    messagingSenderId: '130125072749',
    projectId: 'compraschabelyacerpro',
    authDomain: 'compraschabelyacerpro.firebaseapp.com',
    databaseURL: 'https://compraschabelyacerpro-default-rtdb.firebaseio.com',
    storageBucket: 'compraschabelyacerpro.firebasestorage.app',
    measurementId: 'G-2NBVQD0SS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmGEIZiC7OD4atyqKIiBCU-2Tdmk8DiD8',
    appId: '1:130125072749:android:331c3e9d85ed91898b7264',
    messagingSenderId: '130125072749',
    projectId: 'compraschabelyacerpro',
    databaseURL: 'https://compraschabelyacerpro-default-rtdb.firebaseio.com',
    storageBucket: 'compraschabelyacerpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxzLwiQ8ayGCs1wOyAsh8Ct8Xl2L-7gEY',
    appId: '1:130125072749:ios:626f7a5121c795508b7264',
    messagingSenderId: '130125072749',
    projectId: 'compraschabelyacerpro',
    databaseURL: 'https://compraschabelyacerpro-default-rtdb.firebaseio.com',
    storageBucket: 'compraschabelyacerpro.firebasestorage.app',
    iosClientId: '130125072749-0s9mlicak2bfscjucqudsi8hcgslpl5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemaCompras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxzLwiQ8ayGCs1wOyAsh8Ct8Xl2L-7gEY',
    appId: '1:130125072749:ios:626f7a5121c795508b7264',
    messagingSenderId: '130125072749',
    projectId: 'compraschabelyacerpro',
    databaseURL: 'https://compraschabelyacerpro-default-rtdb.firebaseio.com',
    storageBucket: 'compraschabelyacerpro.firebasestorage.app',
    iosClientId: '130125072749-0s9mlicak2bfscjucqudsi8hcgslpl5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemaCompras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqGlqXBMHtpBBWX80MDNJXiFkU89spXpg',
    appId: '1:130125072749:web:05e7f238d9c1173d8b7264',
    messagingSenderId: '130125072749',
    projectId: 'compraschabelyacerpro',
    authDomain: 'compraschabelyacerpro.firebaseapp.com',
    databaseURL: 'https://compraschabelyacerpro-default-rtdb.firebaseio.com',
    storageBucket: 'compraschabelyacerpro.firebasestorage.app',
    measurementId: 'G-9TXERRMC45',
  );

}